command_timeout = 1000
add_newline = true

format = """
[╭─](color2)\
    $username\
    [ @ ](color7)\
    $hostname \
    $directory      
([│](color2)\
    $git_branch\
    $git_status
)([│](color2)\
    $python\
    $docker_context
)[╰─](color2)\
    $cmd_duration\
    [ > ](color3)
"""

palette = "pywal"

[palettes.pywal]
color0="#030A16"
color1="#0C4B71"
color2="#338F6E"
color3="#10519F"
color4="#0F6297"
color5="#2192A3"
color6="#48BABB"
color7="#c0c1c4"
color8="#424750"

[username]
show_always = true
format = " [$user](color1)"

[hostname]
ssh_only= false
format = "[$hostname](color1) "

[directory]
disabled = false
read_only = ""
truncation_length = 4
truncate_to_repo = false
format = "[$read_only](color4)[$path](color4) "

[cmd_duration]
disabled = false
min_time = 2000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 45_000
format = "[  $duration](color3)"

[git_status]
stashed = " \\(${count}\\)"
ahead = " ↑ ${count}"
behind = " ↓ ${count}"
diverged = " ⇕ ${ahead_count} ${behind_count}"
conflicted = "\\(${count}\\)"
deleted = " \\(${count}\\)"
renamed = " ${count}"
modified = " \\(${count}\\)"
staged = " \\${count}\\)"
untracked = " ?\\(${count}\\)"
format = "([$all_status$ahead_behind](color4)) "

[git_branch]
symbol = "  "
format = "[$symbol](color3)[$branch](color7)"

[docker_context]
symbol = "  "
format = "[$symbol](color3)[$context](color7)"

#=== languages ===

[python]
symbol = "  "
pyenv_prefix = 'pyenv '
python_binary = "python"
format = '[$symbol](color3)[$pyenv_prefix$version(\($virtualenv\))](color7)'
